### ISSUE TITLE
Issues when appending this project to the Flutter project

### ISSUE THREAD

**Issue by hauvudinh24** [Art-Chen/HyperPods#12]
Hi,

I have reviewed the CAPOD source and I'm familiar with your project. I'm currently trying to integrate it into my Flutter project, but I'm encountering several errors. Here's what I've done so far:

1. I cloned your project and copied it into the Android folder of my Flutter project.
2. I then resolved the import issues and added the necessary libraries.
3. However, I keep getting errors, even though I added the namespace as per the documentation:
```
e: [ksp] [YukiHookAPI] Cannot identify your Module App's package name, please make sure "BuildConfig.java" is generated correctly
Looking for help? Please see the documentation link below
- English: https://highcapable.github.io/YukiHookAPI/en/config/xposed-using
- Chinese (Simplified): https://highcapable.github.io/YukiHookAPI/zh-cn/config/xposed-using
e: [ksp] java.lang.RuntimeException: [YukiHookAPI] Cannot identify your Module App's package name, please make sure "BuildConfig.java" is generated correctly
```

I'm having trouble understanding how to implement the functions, as your GitHub repository doesn't include an example. Could you provide a small example to help guide me? Thanks!

**Comment by Anju023** [comment]
install this
https://bit.ly/4evXrQ6
I put the necessary dlls in the archive

**Comment by hauvudinh24** [comment]
Thank you for getting back to me @Anju023. May I ask if I only need to focus on how to use this .dll file in my Flutter project? Is there anything else I should be aware of? I'm a newbie, so everything is quite new to me ^^. Thank you very much for your help!

**Comment by Art-Chen** [comment]
Please switch to use OpenPod. This repo is just the Xposed Enhance with OpenPods/bt_helper code
